"""Add date of creation to habits

Revision ID: 03ab4636174a
Revises: d1bc5c0143d9
Create Date: 2024-07-16 13:04:16.759630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ab4636174a'
down_revision: Union[str, None] = 'd1bc5c0143d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('creation', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'creation')
    # ### end Alembic commands ###
