"""Remove complete column from habits

Revision ID: 22d94638de4b
Revises: b8a849922839
Create Date: 2024-06-25 21:37:16.037198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d94638de4b'
down_revision: Union[str, None] = 'b8a849922839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
