"""Rename columns

Revision ID: 61880c6e4b58
Revises: d2a3b907ac55
Create Date: 2024-07-16 13:09:35.524825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61880c6e4b58'
down_revision: Union[str, None] = 'd2a3b907ac55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('creation_date', sa.Date(), nullable=True))
    op.add_column('habits', sa.Column('days_of_week', sa.Integer(), nullable=True))
    op.drop_column('habits', 'creation')
    op.drop_column('habits', 'days')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('habits', sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('habits', sa.Column('creation', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('habits', 'days_of_week')
    op.drop_column('habits', 'creation_date')
    # ### end Alembic commands ###
