"""Sync Differences

Revision ID: b8a849922839
Revises: 91913b40fbb3
Create Date: 2024-06-24 19:32:47.439932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a849922839'
down_revision: Union[str, None] = '91913b40fbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_habit_id', 'complete', type_='foreignkey')
    op.drop_constraint('fk_user_id', 'complete', type_='foreignkey')
    op.create_foreign_key(None, 'complete', 'habits', ['habit_id'], ['id'])
    op.create_foreign_key(None, 'complete', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_constraint(None, 'complete', type_='foreignkey')
    op.drop_constraint(None, 'complete', type_='foreignkey')
    op.create_foreign_key('fk_user_id', 'complete', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_habit_id', 'complete', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
