"""Create relationship between Users and Complete

Revision ID: d1bc5c0143d9
Revises: e3a43f7da035
Create Date: 2024-07-16 12:15:29.755490

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1bc5c0143d9"
down_revision: Union[str, None] = "e3a43f7da035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("complete", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "complete", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "complete", type_="foreignkey")
    op.drop_column("complete", "user_id")
    # ### end Alembic commands ###
