"""Add completion days to habits

Revision ID: d2a3b907ac55
Revises: 03ab4636174a
Create Date: 2024-07-16 13:08:33.008613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a3b907ac55'
down_revision: Union[str, None] = '03ab4636174a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'days')
    # ### end Alembic commands ###
